"""The gap taxonomy, derived from the corpus rather than written in advance.

Section 1 says no standard taxonomy exists and each auditor describes a gap in
their own words. The tests that matter are therefore not "does it return
categories" but: does the set actually come from the findings, is it frozen once
derived, and does classification refuse to proceed without one — because a
silent fallback list is exactly what this stage exists to remove.
"""

from datetime import date

import pytest

from sentinelops.entities import GapCategory
from sentinelops.llm.prompts import taxonomy as prompts
from sentinelops.repositories import repositories
from sentinelops.stages import intelligence, taxonomy
from sentinelops.synth import generate_corpus, seed_database
from sentinelops.synth.calendar import SIMULATED_TODAY

AS_OF = SIMULATED_TODAY


@pytest.fixture(scope="module")
def corpus():
    return generate_corpus()


@pytest.fixture
def seeded(conn, corpus):
    seed_database(conn, corpus)
    return conn


@pytest.fixture
def derived(seeded):
    return seeded, taxonomy.derive(seeded, AS_OF)


# --- the set comes off the corpus --------------------------------------------

def test_the_taxonomy_is_derived_not_declared(derived):
    conn, report = derived
    assert report.categories
    assert prompts.MIN_CATEGORIES <= len(report.categories) <= prompts.MAX_CATEGORIES
    for category in report.categories:
        assert isinstance(category, GapCategory)
        assert category.id == taxonomy.slug(category.id), "ids are slugs"
        assert category.definition.strip()
        assert category.definition.strip().lower() != category.id.replace("_", " ")


def test_no_category_name_is_hardcoded_in_the_package():
    """The point of the slice, asserted against the source.

    If a category list reappears in the prompt package or the stage, the
    derivation is decoration. The fake provider is exempt and says why in its
    own comments: it is standing in for a model, and a model has vocabulary.
    """
    import ast
    from pathlib import Path

    root = Path(__file__).resolve().parents[1] / "src" / "sentinelops"
    for path in (root / "llm" / "prompts" / "triage.py",
                 root / "llm" / "prompts" / "taxonomy.py",
                 root / "stages" / "taxonomy.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.Assign):
                continue
            names = {t.id for t in node.targets if isinstance(t, ast.Name)}
            if not names & {"GAP_CATEGORIES", "CATEGORY_DEFINITIONS"}:
                continue
            raise AssertionError(
                f"{path.name} still declares {names}; the taxonomy is supposed "
                f"to come from the corpus"
            )


def test_the_categories_reflect_what_the_corpus_actually_contains(derived):
    """Not just any six-to-twelve names: ones the findings support.

    The corpus is full of access left with leavers, so a set that cannot
    express that is not a set derived from this corpus.
    """
    conn, report = derived
    ids = set(taxonomy.names(conn))
    assert any("access" in name for name in ids), sorted(ids)
    text = " ".join(
        f.description.lower() for f in repositories(conn)["findings"].list()
        if f.source == "audit"
    )
    for name in ids:
        stems = [word for word in name.split("_") if len(word) > 4]
        assert any(stem[:6] in text for stem in stems) or not stems, (
            f"{name} names something the findings never mention"
        )


def test_only_audit_track_descriptions_are_read(seeded):
    """Activity-track descriptions are generated by this system.

    Inducing a taxonomy from them would be reading our own template back and
    calling it the organisation's vocabulary.
    """
    repo = repositories(seeded)
    eligible = {fid for fid, _ in taxonomy.eligible_descriptions(repo)}
    for finding in repo["findings"].list():
        if finding.source != "audit":
            assert finding.id not in eligible


def test_it_is_batched_and_then_consolidated(derived):
    """Two phases, and the second one has something to do."""
    conn, report = derived
    assert report.batches > 1, "one batch means the consolidation is ceremony"
    assert report.model_calls == report.batches + 1, "propose per batch, then one merge"
    assert report.proposed >= len(report.categories)


# --- frozen ------------------------------------------------------------------

def test_deriving_twice_spends_nothing_and_returns_the_same_set(derived):
    conn, first = derived
    before = conn.execute("SELECT COUNT(*) c FROM token_usage").fetchone()["c"]
    second = taxonomy.derive(conn, AS_OF)
    after = conn.execute("SELECT COUNT(*) c FROM token_usage").fetchone()["c"]

    assert after == before, "a second derive must not pay to re-read the corpus"
    assert second.version == first.version
    assert [c.id for c in second.categories] == [c.id for c in first.categories]


def test_the_version_is_a_hash_of_the_outcome_not_a_timestamp(seeded):
    """So rederiving over an unchanged corpus does not orphan every category.

    A timestamped version would make every rerun look like a new taxonomy and
    every `gap_category` recorded against the old one look stale.
    """
    first = taxonomy.derive(seeded, AS_OF)
    second = taxonomy.derive(seeded, date(2027, 6, 1), force=True)
    assert second.version == first.version


def test_the_trail_records_where_the_categories_came_from(derived):
    conn, report = derived
    events = [
        e for e in repositories(conn)["audit"].read_all()
        if e.action == "taxonomy_derived"
    ]
    assert len(events) == 1
    detail = events[0].detail
    assert detail["taxonomy_version"] == report.version
    assert detail["derived_from_findings"] == report.descriptions_read
    assert sorted(detail["categories"]) == sorted(c.id for c in report.categories)
    assert events[0].ts.date() == AS_OF, "simulated time, not the wall clock"


# --- no silent fallback ------------------------------------------------------

def test_classifying_without_a_taxonomy_is_refused(seeded):
    """The whole slice in one assertion.

    Before this, an undecided taxonomy meant classifying against ten categories
    somebody wrote at a desk. Now it means stopping.
    """
    with pytest.raises(ValueError) as refused:
        intelligence.classify(seeded, AS_OF)
    assert "no gap taxonomy has been derived" in str(refused.value)
    assert "no hardcoded fallback" in str(refused.value)


def test_a_catch_all_category_is_dropped(derived):
    """Every hard finding would land in it and the taxonomy would stop meaning
    anything. The prompt forbids it; this makes the refusal structural."""
    conn, _ = derived
    frozen = taxonomy._freeze([
        {"name": "Access Not Revoked", "definition": "d"},
        {"name": "Other", "definition": "anything else"},
        {"name": "miscellaneous", "definition": "the rest"},
    ], read=10)
    assert [c["id"] for c in frozen] == ["access_not_revoked"]


def test_names_that_differ_only_in_shape_become_one_category():
    """'Access Not Revoked', 'access-not-revoked' and 'access not revoked'."""
    frozen = taxonomy._freeze([
        {"name": "Access Not Revoked", "definition": "first"},
        {"name": "access-not-revoked", "definition": "second"},
        {"name": "access not revoked", "definition": "third"},
    ], read=3)
    assert len(frozen) == 1
    assert frozen[0]["id"] == "access_not_revoked"


def test_a_set_outside_the_working_range_is_refused(seeded, monkeypatch):
    """Two buckets for everything, or hair-splitting nobody does."""
    monkeypatch.setattr(
        taxonomy, "_consolidate",
        lambda conn, client, proposals, report: [
            {"name": "everything", "definition": "all of it"},
        ],
    )
    from sentinelops.llm.protocol import LlmError
    with pytest.raises(LlmError) as refused:
        taxonomy.derive(seeded, AS_OF, force=True)
    assert "working range" in str(refused.value)


# --- cost --------------------------------------------------------------------

def test_derivation_is_metered(derived):
    conn, report = derived
    rows = conn.execute(
        "SELECT label FROM token_usage WHERE label LIKE 'TAXONOMY:%'"
    ).fetchall()
    assert len(rows) == report.model_calls
    assert any("consolidate" in row["label"] for row in rows)


def test_the_printable_table_names_the_version_and_the_sample(derived):
    conn, report = derived
    table = taxonomy.printable(conn)
    assert report.version in table
    assert str(report.descriptions_read) in table
    for category in report.categories:
        assert category.id in table


# --- the interaction the derived taxonomy exposed ----------------------------

def test_the_activity_track_cannot_crowd_out_an_audit_prior(seeded):
    """The candidate shortlist is capped, so what fills it decides what is seen.

    Capping on age alone let the activity track win on volume: it produces
    hundreds of findings a year against the audit track's dozens, so twelve
    slots filled with system-generated descriptions and the auditor-written
    prior that is the real recurrence never reached the model. Invisible while
    the taxonomy was hardcoded, because activity findings piled into a category
    the audit track barely used; deriving the categories redistributed them and
    recall fell from 50% to 16.7%.
    """
    from datetime import datetime, timedelta

    from sentinelops.entities import Finding
    from sentinelops.llm.prompts.recurrence import MAX_CANDIDATES
    from sentinelops.repositories import simulated_clock

    taxonomy.derive(seeded, AS_OF)
    intelligence.classify(seeded, AS_OF)
    repo = repositories(seeded)

    subject = next(
        f for f in sorted(repo["findings"].list(), key=lambda f: f.raised_at,
                          reverse=True)
        if f.source == "audit" and f.gap_category
    )
    prior = next(
        f for f in repo["findings"].list()
        if f.source == "audit"
        and f.gap_category == subject.gap_category
        and f.raised_at < subject.raised_at
        and f.id != subject.id
    )

    # bury it under far more activity-track findings, all older, all sharing
    # the category — exactly the shape a full pipeline run produces
    oldest = min(f.raised_at for f in repo["findings"].list())
    with simulated_clock(oldest):
        for n in range(MAX_CANDIDATES * 3):
            repo["findings"].add(Finding(
                id=f"FND-NOISE-{n:03d}",
                source="activity_assessment",
                auditable_unit_id="AREA-FINANCE",
                description="Generated description from a control clause.",
                raised_by="ID-SYSTEM",
                raised_at=oldest - timedelta(days=n + 1),
                owner_identity=subject.owner_identity,
                target_date=subject.target_date,
                gap_category=subject.gap_category,
                severity="Minor",
            ))

    shortlist = intelligence.candidates_for(repo, subject)
    assert len(shortlist) <= MAX_CANDIDATES
    assert prior.id in {f.id for f in shortlist}, (
        "an auditor-written prior was pushed off the shortlist by activity-track "
        "volume; the model never gets to see the recurrence it is there to find"
    )
