"""Where a programme's schedule window is kept, so the pipeline never assumes one.

The corpus is generated by `synth/`, and the pipeline must not import the
test-data package to find out what it covers — that is why period arithmetic
moved to `periods.py` in slice 4. So the window is written into the database
when the corpus is seeded, and S1, S2 and remediation read it back from there.

A database with no window recorded refuses to schedule rather than guessing.
Guessing is how this was wrong for six slices: S1 guessed 2026.
"""

from __future__ import annotations

from datetime import date

from .periods import Window


class WindowNotRecorded(RuntimeError):
    """Nothing has said what span this programme covers."""


def record(conn, window: Window, *, source: str) -> Window:
    """Store the window. One row; recording again replaces it."""
    conn.execute(
        "INSERT INTO schedule_window (id, start_date, end_date, source) "
        "VALUES (1, ?, ?, ?) "
        "ON CONFLICT(id) DO UPDATE SET start_date = excluded.start_date, "
        "end_date = excluded.end_date, source = excluded.source",
        (window.start.isoformat(), window.end.isoformat(), source),
    )
    conn.commit()
    return window


def load(conn) -> Window:
    row = conn.execute(
        "SELECT start_date, end_date FROM schedule_window WHERE id = 1"
    ).fetchone()
    if row is None:
        raise WindowNotRecorded(
            "no schedule window is recorded in this database. Seed a corpus, or "
            "call sentinelops.window.record(conn, Window(start, end), source=...) "
            "— the scheduler will not assume a year"
        )
    return Window(
        date.fromisoformat(row["start_date"]), date.fromisoformat(row["end_date"])
    )
