"""Deriving the gap taxonomy from the corpus, then freezing it.

Section 1: *no standard gap taxonomy exists. The auditor describes each gap in
their own words.* An earlier slice answered that with ten categories written
into the prompt package, labelled honestly as ours. Honest about provenance,
still wrong in kind — a taxonomy invented at a desk names the failures somebody
imagined, and against an organisation whose findings are about something else
every category is a near-miss.

This reads the categories off the findings instead. Two model calls of work:

  **propose**      batches of real descriptions, each asked what kinds of
                   failure it contains. Batches see only their own findings, so
                   the proposals genuinely differ and there is something to
                   reconcile.
  **consolidate**  every proposal at once, merged into one closed set.

**Deterministic either side of the model.** Which findings are eligible (audit
track only — activity-track descriptions are generated by this system, so
inducing a taxonomy from them would be reading our own template back), how they
are batched, the slug each name becomes, the bounds on the set, and the refusal
to accept a set that violates them. The model is asked the one question a rule
cannot answer: which of these differently-worded failures are the same failure.

**Frozen once derived.** `taxonomy_version` stamps the run; classification
records the version it judged against. A taxonomy that drifted between findings
would make `gap_category` incomparable across eighteen months, and recurrence
reads that field — vocabulary drift would surface as recurring gaps.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from datetime import date, datetime, time
from typing import Any

from ..entities import GapCategory
from ..llm import TokenMeter, get_client
from ..llm.parsing import extract_json, validate
from ..llm.prompts.taxonomy import (
    BATCH_SIZE,
    CONSOLIDATE_MAX_TOKENS,
    CONSOLIDATE_SYSTEM_V1,
    MAX_CATEGORIES,
    MIN_CATEGORIES,
    PROMPT_VERSION,
    PROPOSE_MAX_TOKENS,
    PROPOSE_SYSTEM_V1,
    consolidate_schema_v1,
    consolidate_user_v1,
    propose_schema_v1,
    propose_user_v1,
)
from ..llm.protocol import LlmError, LlmRequest

#: Names arrive as prose and become identifiers. Done here rather than trusted
#: from the model, so "Access Not Revoked", "access-not-revoked" and
#: "access not revoked" cannot become three categories.
_SLUG_STRIP = re.compile(r"[^a-z0-9]+")


@dataclass
class TaxonomyReport:
    as_of: date
    version: str = ""
    categories: list[GapCategory] = field(default_factory=list)
    proposed: int = 0
    batches: int = 0
    model_calls: int = 0
    descriptions_read: int = 0

    def summary(self) -> str:
        return (
            f"{len(self.categories)} categories from {self.descriptions_read} "
            f"findings in {self.batches} batch(es), {self.proposed} proposals "
            f"merged, {self.model_calls} model call(s)"
        )


def slug(name: str) -> str:
    """`Access Not Revoked` -> `access_not_revoked`."""
    return _SLUG_STRIP.sub("_", name.strip().lower()).strip("_")


def eligible_descriptions(repo) -> list[tuple[str, str]]:
    """(finding id, description) for every finding a taxonomy may be read from.

    Audit track only. Activity-track findings carry a description this system
    generated from a control title and a failing clause — inducing categories
    from those would be reading our own template back and calling it the
    organisation's vocabulary.
    """
    return sorted(
        (f.id, f.description)
        for f in repo["findings"].list()
        if f.source == "audit" and f.description.strip()
    )


def batches(items: list[Any], size: int = BATCH_SIZE) -> list[list[Any]]:
    return [items[n:n + size] for n in range(0, len(items), size)]


def _version_for(names: list[str], count: int) -> str:
    """A version that changes when the derived set changes, and not otherwise.

    A timestamp would make every rerun a new version and every stored
    `gap_category` look stale; a hash of the outcome means rederiving over an
    unchanged corpus lands on the same version and classifications stay valid.
    """
    digest = hashlib.sha256(
        ("|".join(sorted(names)) + f"#{count}").encode("utf-8")
    ).hexdigest()[:12]
    return f"tax-{digest}"


def _ask(conn, client, request: LlmRequest, label: str) -> tuple[dict[str, Any], Any]:
    with TokenMeter(conn, tier="triage", label=f"TAXONOMY:{label}") as meter:
        response = meter.record(client.complete(request))
    payload = response.parsed_json or extract_json(response.text)
    if payload is None:
        raise LlmError(f"taxonomy {label} returned no readable JSON")
    return validate(payload, request.response_schema), response


def _propose(conn, client, descriptions: list[str], report: TaxonomyReport):
    request = LlmRequest(
        system=PROPOSE_SYSTEM_V1,
        messages=[{"role": "user", "content": propose_user_v1(descriptions)}],
        max_tokens=PROPOSE_MAX_TOKENS,
        response_schema=propose_schema_v1(),
        tier="triage",
    )
    payload, _ = _ask(conn, client, request, f"propose[{len(descriptions)}]")
    report.model_calls += 1
    return [
        {"name": item["name"], "definition": item["definition"]}
        for item in payload["categories"]
    ]


def _consolidate(conn, client, proposals, report: TaxonomyReport):
    request = LlmRequest(
        system=CONSOLIDATE_SYSTEM_V1,
        messages=[{"role": "user", "content": consolidate_user_v1(proposals)}],
        max_tokens=CONSOLIDATE_MAX_TOKENS,
        response_schema=consolidate_schema_v1(),
        tier="triage",
    )
    payload, _ = _ask(conn, client, request, f"consolidate[{len(proposals)}]")
    report.model_calls += 1
    return payload["categories"]


def derive(
    conn,
    as_of: date,
    *,
    client=None,
    force: bool = False,
) -> TaxonomyReport:
    """Read a working taxonomy off the corpus and freeze it.

    Idempotent by default: if a taxonomy is already frozen this returns it
    without spending anything, because deriving on every cycle would both cost
    money and risk moving the vocabulary underneath findings already classified.
    `force=True` rederives, which is what a corpus reshape needs.
    """
    from ..repositories import repositories, simulated_clock

    repo = repositories(conn)
    existing = current(conn)
    if existing and not force:
        return TaxonomyReport(
            as_of=as_of, version=existing[0].taxonomy_version,
            categories=existing, descriptions_read=existing[0].derived_from_count,
        )

    client = client or get_client()
    rows = eligible_descriptions(repo)
    report = TaxonomyReport(as_of=as_of, descriptions_read=len(rows))
    if not rows:
        raise ValueError(
            "no audit-track findings to derive a taxonomy from; a taxonomy read "
            "off an empty corpus would be the hardcoded list wearing a hat"
        )

    groups = batches([text for _, text in rows])
    report.batches = len(groups)
    proposals = [_propose(conn, client, group, report) for group in groups]
    report.proposed = sum(len(p) for p in proposals)

    merged = _consolidate(conn, client, proposals, report)
    categories = _freeze(merged, len(rows))
    if not MIN_CATEGORIES <= len(categories) <= MAX_CATEGORIES:
        raise LlmError(
            f"derived taxonomy has {len(categories)} categories; the working "
            f"range is {MIN_CATEGORIES}-{MAX_CATEGORIES}. A set outside it is "
            f"either two buckets for everything or hair-splitting nobody does"
        )

    # Sorted before storing, so a fresh derivation and a cached one hand back
    # the same order. `current()` sorts on read; without this the two paths
    # disagreed and only the cache looked stable.
    categories.sort(key=lambda entry: entry["id"])
    version = _version_for([c["id"] for c in categories], len(rows))
    stamp = datetime.combine(as_of, time(7, 0))
    report.version = version

    with simulated_clock(stamp):
        # A forced rederivation over an unchanged corpus lands on the same
        # content-addressed version, so the rows for it already exist. Replacing
        # them is the whole point of `force` and colliding on the primary key
        # helps nobody; the audit event below still records that it was rerun.
        conn.execute(
            "DELETE FROM gap_categories WHERE taxonomy_version = ?", (version,)
        )
        for entry in categories:
            record = GapCategory(
                id=entry["id"],
                label=entry["label"],
                definition=entry["definition"],
                taxonomy_version=version,
                derived_at=stamp,
                derived_from_count=len(rows),
                merged_from=entry["merged_from"],
                prompt_version=PROMPT_VERSION,
            )
            repo["categories"].add(record)
            report.categories.append(record)

        repo["audit"].append(
            actor="ai", owner="taxonomy",
            action="taxonomy_derived", entity_type="GapCategory",
            entity_id=version,
            detail={
                "taxonomy_version": version,
                "categories": [c.id for c in report.categories],
                "derived_from_findings": len(rows),
                "batches": report.batches,
                "proposals_merged": report.proposed,
                "model_calls": report.model_calls,
                "prompt_version": PROMPT_VERSION,
                "note": (
                    "categories induced from the corpus, not supplied by the "
                    "organisation, which has no taxonomy of its own"
                ),
            },
        )
    return report


def _freeze(merged: list[dict[str, Any]], read: int) -> list[dict[str, Any]]:
    """Slug the names, drop duplicates and catch-alls, keep the order stable."""
    out: dict[str, dict[str, Any]] = {}
    for entry in merged:
        key = slug(entry["name"])
        if not key or key in {"other", "miscellaneous", "uncategorised",
                              "uncategorized", "general"}:
            # The prompt forbids a catch-all; a model that supplies one anyway
            # must not have it silently accepted, because every hard finding
            # would land there and the taxonomy would stop meaning anything.
            continue
        if key in out:
            out[key]["merged_from"].extend(entry.get("merged_from", []))
            continue
        out[key] = {
            "id": key,
            "label": entry["name"].strip(),
            "definition": entry["definition"].strip(),
            "merged_from": sorted({
                slug(name) for name in entry.get("merged_from", []) if name
            }),
        }
    return list(out.values())


# --- reading ------------------------------------------------------------------

def current(conn) -> list[GapCategory]:
    """The frozen set, newest version. Empty until something has derived one."""
    from ..repositories import repositories

    rows = repositories(conn)["categories"].list()
    if not rows:
        return []
    newest = max(rows, key=lambda c: (c.derived_at, c.taxonomy_version))
    return sorted(
        (c for c in rows if c.taxonomy_version == newest.taxonomy_version),
        key=lambda c: c.id,
    )


def names(conn) -> tuple[str, ...]:
    return tuple(c.id for c in current(conn))


def definitions(conn) -> dict[str, str]:
    return {c.id: c.definition for c in current(conn)}


def version(conn) -> str:
    rows = current(conn)
    return rows[0].taxonomy_version if rows else ""


def require(conn) -> list[GapCategory]:
    """The taxonomy, or a refusal that says what to do about it."""
    rows = current(conn)
    if not rows:
        raise ValueError(
            "no gap taxonomy has been derived; run taxonomy.derive() before "
            "classifying. There is deliberately no hardcoded fallback — a "
            "silent default list is the thing this stage exists to remove"
        )
    return rows


def printable(conn) -> str:
    """The derived set, for a human to read and argue with."""
    rows = current(conn)
    if not rows:
        return "no taxonomy derived"
    width = max(len(c.id) for c in rows)
    lines = [
        f"taxonomy {rows[0].taxonomy_version}  "
        f"({len(rows)} categories, read off {rows[0].derived_from_count} "
        f"audit findings, prompt {rows[0].prompt_version})",
        "",
    ]
    for category in rows:
        lines.append(f"  {category.id:<{width}}  {category.definition}")
        if category.merged_from:
            lines.append(
                f"  {'':<{width}}  merged: {', '.join(category.merged_from)}"
            )
    return "\n".join(lines)
